// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateTotals(arg1) {
  return window['go']['main']['App']['CalculateTotals'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetAllInvoices() {
  return window['go']['main']['App']['GetAllInvoices']();
}

export function GetAllProducts() {
  return window['go']['main']['App']['GetAllProducts']();
}

export function GetInvoiceByID(arg1) {
  return window['go']['main']['App']['GetInvoiceByID'](arg1);
}

export function GetTotalInWords(arg1) {
  return window['go']['main']['App']['GetTotalInWords'](arg1);
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}
