// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateTotals(arg1) {
  return window['go']['main']['App']['CalculateTotals'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateInvoice(arg1) {
  return window['go']['main']['App']['CreateInvoice'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetAllClients() {
  return window['go']['main']['App']['GetAllClients']();
}

export function GetAllInvoices(arg1) {
  return window['go']['main']['App']['GetAllInvoices'](arg1);
}

export function GetAllProducts() {
  return window['go']['main']['App']['GetAllProducts']();
}

export function GetAvailableYears() {
  return window['go']['main']['App']['GetAvailableYears']();
}

export function GetDashboardStats(arg1) {
  return window['go']['main']['App']['GetDashboardStats'](arg1);
}

export function GetInvoiceByID(arg1) {
  return window['go']['main']['App']['GetInvoiceByID'](arg1);
}

export function GetTotalInWords(arg1) {
  return window['go']['main']['App']['GetTotalInWords'](arg1);
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}

export function SearchClients(arg1) {
  return window['go']['main']['App']['SearchClients'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateInvoice(arg1, arg2) {
  return window['go']['main']['App']['UpdateInvoice'](arg1, arg2);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}
