// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {invoice} from '../models';
import {inventory} from '../models';
import {main} from '../models';

export function CalculateTotals(arg1:number):Promise<Record<string, any>>;

export function CreateClient(arg1:client.Client):Promise<void>;

export function CreateInvoice(arg1:invoice.InvoiceCreateRequest):Promise<invoice.InvoiceResponse>;

export function CreateProduct(arg1:inventory.Product):Promise<inventory.Product>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GeneratePDF(arg1:number):Promise<string>;

export function GetAllClients():Promise<Array<client.Client>>;

export function GetAllInvoices(arg1:number):Promise<Array<invoice.InvoiceResponse>>;

export function GetAllProducts():Promise<Array<inventory.Product>>;

export function GetAvailableYears():Promise<Array<number>>;

export function GetDashboardStats(arg1:number):Promise<main.DashboardStats>;

export function GetInvoiceByID(arg1:number):Promise<invoice.InvoiceResponse>;

export function GetTotalInWords(arg1:number):Promise<string>;

export function OpenPDF(arg1:string):Promise<void>;

export function SearchClients(arg1:string):Promise<Array<client.Client>>;

export function UpdateClient(arg1:client.Client):Promise<void>;

export function UpdateInvoice(arg1:number,arg2:invoice.InvoiceCreateRequest):Promise<invoice.InvoiceResponse>;

export function UpdateProduct(arg1:inventory.Product):Promise<void>;
