// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {invoice} from '../models';

export function CalculateTotals(arg1:number):Promise<{[key: string]: any}>;

export function CreateInvoice(arg1:invoice.InvoiceCreateRequest):Promise<invoice.InvoiceResponse>;

export function GeneratePDF(arg1:number):Promise<string>;

export function GetAllInvoices():Promise<Array<invoice.InvoiceResponse>>;

export function GetInvoiceByID(arg1:number):Promise<invoice.InvoiceResponse>;

export function GetTotalInWords(arg1:number):Promise<string>;

export function OpenPDF(arg1:string):Promise<void>;
